version: '3.9'

services:
  dev:
    image: node:16.17.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -c "yarn install && yarn start; tail -f"
    environment:
      HOST: 0.0.0.0
    ports:
    - 13000:3000

