version: '3.9'

services:
  dev:
    image: node:16.17.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -c "yarn install && yarn start; tail -f"
    environment:
      HOST: 0.0.0.0
    ports:
    - 13000:3000

  unit:
    image: node:16.17.1
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -c "yarn install && yarn test:watch; tail -f"

  e2e:
    image: cypress/included:10.9.0
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -c "yarn install && yarn cypress; tail -f"
    environment:
      CYPRESS_BASE_URL: http://dev:3000

  build:
    image: node:16.17.1-bullseye-slim
    volumes:
    - .:/ws
    working_dir: /ws/opinion-ate
    entrypoint: bash -c "yarn install && yarn build; tail -f"
